# Generated by Django 5.1.6 on 2025-02-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordemPremio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroEdicao', models.IntegerField()),
                ('anoEdicao', models.IntegerField()),
                ('dataEdicao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dezena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dezenas', to='usuario.premio')),
            ],
        ),
        migrations.AddField(
            model_name='premio',
            name='sorteio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='usuario.sorteio'),
        ),
    ]
